// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/protobuf.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac732507fd34a3d2, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac732507fd34a3d2, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac732507fd34a3d2, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type FetchUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchUserRequest) Reset()         { *m = FetchUserRequest{} }
func (m *FetchUserRequest) String() string { return proto.CompactTextString(m) }
func (*FetchUserRequest) ProtoMessage()    {}
func (*FetchUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac732507fd34a3d2, []int{3}
}

func (m *FetchUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchUserRequest.Unmarshal(m, b)
}
func (m *FetchUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchUserRequest.Marshal(b, m, deterministic)
}
func (m *FetchUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchUserRequest.Merge(m, src)
}
func (m *FetchUserRequest) XXX_Size() int {
	return xxx_messageInfo_FetchUserRequest.Size(m)
}
func (m *FetchUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchUserRequest proto.InternalMessageInfo

func (m *FetchUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type FetchUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchUserResponse) Reset()         { *m = FetchUserResponse{} }
func (m *FetchUserResponse) String() string { return proto.CompactTextString(m) }
func (*FetchUserResponse) ProtoMessage()    {}
func (*FetchUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac732507fd34a3d2, []int{4}
}

func (m *FetchUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchUserResponse.Unmarshal(m, b)
}
func (m *FetchUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchUserResponse.Marshal(b, m, deterministic)
}
func (m *FetchUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchUserResponse.Merge(m, src)
}
func (m *FetchUserResponse) XXX_Size() int {
	return xxx_messageInfo_FetchUserResponse.Size(m)
}
func (m *FetchUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchUserResponse proto.InternalMessageInfo

func (m *FetchUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac732507fd34a3d2, []int{5}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type DeleteUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac732507fd34a3d2, []int{6}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac732507fd34a3d2, []int{7}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac732507fd34a3d2, []int{8}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "protobuf.User")
	proto.RegisterType((*CreateUserRequest)(nil), "protobuf.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "protobuf.CreateUserResponse")
	proto.RegisterType((*FetchUserRequest)(nil), "protobuf.FetchUserRequest")
	proto.RegisterType((*FetchUserResponse)(nil), "protobuf.FetchUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "protobuf.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "protobuf.DeleteUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "protobuf.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "protobuf.UpdateUserResponse")
}

func init() { proto.RegisterFile("protobuf/protobuf.proto", fileDescriptor_ac732507fd34a3d2) }

var fileDescriptor_ac732507fd34a3d2 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xa5, 0x15, 0x0c, 0x0c, 0x09, 0xb1, 0x13, 0x13, 0x9b, 0xe2, 0x81, 0xec, 0xa9, 0x5e, 0x30,
	0xc1, 0x03, 0xdc, 0x35, 0x44, 0xae, 0x35, 0x7c, 0x40, 0xa1, 0x63, 0x6c, 0x82, 0xb6, 0xee, 0xb6,
	0xfa, 0x67, 0x7e, 0x9f, 0x61, 0x1b, 0x76, 0x47, 0xb6, 0x07, 0xf0, 0xb6, 0x93, 0x37, 0xf3, 0xde,
	0xdb, 0xf7, 0xe0, 0xa6, 0x94, 0x45, 0x55, 0x6c, 0xea, 0xd7, 0xfb, 0xc3, 0x63, 0xaa, 0x1f, 0xd8,
	0x3f, 0xcc, 0xe2, 0x19, 0xba, 0x6b, 0x45, 0x12, 0x47, 0xe0, 0xe7, 0x59, 0xe8, 0x4d, 0xbc, 0xb8,
	0x97, 0xf8, 0x79, 0x86, 0x11, 0xf4, 0xcb, 0x54, 0xa9, 0xef, 0x42, 0x66, 0xa1, 0x3f, 0xf1, 0xe2,
	0x41, 0x62, 0x66, 0xbc, 0x86, 0x1e, 0xbd, 0xa7, 0xf9, 0x2e, 0xbc, 0xd0, 0x40, 0x33, 0x88, 0x39,
	0x04, 0x8f, 0x92, 0xd2, 0x8a, 0xf6, 0x7c, 0x09, 0x7d, 0xd6, 0xa4, 0x2a, 0x14, 0xd0, 0xad, 0x15,
	0x49, 0x4d, 0x3c, 0x9c, 0x8d, 0xa6, 0xc6, 0x87, 0x5e, 0xd2, 0x98, 0x58, 0x00, 0xf2, 0x43, 0x55,
	0x16, 0x1f, 0x8a, 0x4e, 0xba, 0x8c, 0xe1, 0x6a, 0x49, 0xd5, 0xf6, 0x8d, 0x2b, 0x1a, 0x73, 0xde,
	0x91, 0x39, 0xb6, 0x79, 0x86, 0xc4, 0x1d, 0x04, 0x4f, 0xb4, 0xa3, 0xbf, 0xbf, 0x6a, 0xd7, 0x58,
	0x00, 0xf2, 0xd5, 0x33, 0x44, 0xe6, 0x10, 0xac, 0xcb, 0xec, 0x7f, 0xd1, 0xf1, 0xc3, 0xd3, 0x25,
	0x67, 0x3f, 0x3e, 0x0c, 0xf7, 0xe3, 0x0b, 0xc9, 0xaf, 0x7c, 0x4b, 0xb8, 0x02, 0xb0, 0x25, 0xe0,
	0xd8, 0xde, 0x38, 0x9d, 0x46, 0xb7, 0xed, 0x60, 0x23, 0x2e, 0x3a, 0xb8, 0x84, 0x81, 0xc9, 0x1a,
	0x23, 0xbb, 0x7c, 0x5c, 0x55, 0x34, 0x6e, 0xc5, 0x0c, 0xcf, 0x0a, 0xc0, 0xe6, 0xc9, 0x2d, 0x39,
	0x85, 0x70, 0x4b, 0x6e, 0x05, 0x0d, 0x95, 0xcd, 0x89, 0x53, 0x39, 0xb1, 0x73, 0x2a, 0x37, 0x5a,
	0xd1, 0xd9, 0x5c, 0x6a, 0xf8, 0xe1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xd5, 0x39, 0xdb, 0x5c,
	0x03, 0x00, 0x00,
}
